# Generated by Django 2.2.6 on 2019-10-22 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('channel', models.CharField(max_length=32)),
                ('account', models.CharField(max_length=32)),
                ('status', models.BooleanField()),
            ],
            options={
                'db_table': 'files',
            },
        ),
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('channel', models.CharField(max_length=32)),
                ('account', models.CharField(max_length=32)),
                ('publish_time', models.CharField(max_length=32)),
                ('publish_freq', models.CharField(max_length=16)),
                ('text', models.TextField(blank=True, max_length=4096, null=True)),
                ('file_amount', models.IntegerField()),
                ('status', models.BooleanField()),
                ('update_ts', models.BigIntegerField()),
                ('update_dt', models.DateField()),
            ],
            options={
                'db_table': 'jobs',
            },
        ),
    ]
